#include "type.h"
void readsector(int, int, int, int, int, int);
void read_sector(int, int, int, int);
void store_pcb(void);
void phys_copy(int, unsigned int, int, unsigned int, unsigned int);
void printc(char);
void printhex(unsigned int);
void printd(unsigned int);
void out_byte(int, char);
char in_byte(int port);
void lock(void);
void unlock(void);
void task_switch(void);
void init(void);
void jumpf(void);
void proc_init(int, int, int);
void init_psw(int);
void send(int, struct msg_type*);
void receive(int, struct msg_type *);
void send_ask(int, struct msg_type*);
void receive_ask(int, struct msg_type*);
void sys_handle(int, int, struct msg_type*);
void kb_driver(void);
void disp_driver(void);
void sys_driver(void);
void init_t_psw(unsigned int, int);
void thread_init(int, unsigned int);
int fork(void);
void exit(void);
void fork_psw(unsigned int, unsigned int, unsigned int);
void exec_stack(int, int ,int);
void exec(char *, void *);
int strlen(char *);
